name: build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: cachix/install-nix-action@v20

    - uses: actions/checkout@v3

    - name: Build module
      run: |
        nix build \
          --json \
          --print-build-logs
